DirectoryPath: public
IgnoreDirectoryMissingTrailingSlash: true
CheckExternal: true
IgnoreAltMissing: true
IgnoreEmptyHref: true
IgnoreURLs:
# We have to ignore this due to rate limiting
- "github.com"
- "packages.timber.io"
- "localhost"
# Somehow this link allows shows up as broken, so we'll exclude it
- "https://www.microsoft.com/en-us/windows"
# Somehow these links always come up as 5xx even though they work fine in the browser
- "maxmind.com"
